### ISSUE TITLE
URL host as suffix (to support subdomains as slugs)

### ISSUE THREAD

**Issue by iDiegoNL** [camya/filament-title-with-slug#7]
Hey,

Awesome package. I've been using it for a few days now, and I'm loving the features.
However, I am missing a feature that could make it a little better. For a project that I'm working on, I am using slugs as subdomains. So e.g. `slug.laravel.test`. From what I can see, it currently only is possible to use slugs as paths, e.g. `laravel.test/slug`.

It would be awesome if something like the following could be implemented:
![image](https://user-images.githubusercontent.com/10339564/202186641-7c4d0844-e2db-45fb-83a5-f3714a32ffca.png)

**Comment by camya** [comment]
Nice idea. I implemented the feature already and committed it to main. Feel free to test it on the main branch.

Documentation ["Use the slug as subdomain"](https://github.com/camya/filament-title-with-slug#use-the-slug-as-subdomain)

Have a nice day. I update the release next week.

**Comment by camya** [comment]
Added in https://github.com/camya/filament-title-with-slug/releases/tag/v0.5.3
